name: ci
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: modules-${{ hashFiles('yarn.lock') }}
          restore-keys: modules-

      - name: Install deps
        run: yarn
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
